import { query } from '../config/db.js'

export async function ensureIdentity() {
  const ddl = `
DO $$
BEGIN
  -- Vendors: add identity on vendor_id if missing
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='vendors' AND column_name='vendor_id' AND is_identity='YES'
  ) THEN
    BEGIN
      EXECUTE 'ALTER TABLE public.vendors ALTER COLUMN vendor_id ADD GENERATED BY DEFAULT AS IDENTITY';
    EXCEPTION WHEN others THEN
      -- Ignore if it's already backed by a default sequence
      NULL;
    END;
  END IF;

  -- Vendors: add primary key if missing
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE table_schema='public' AND table_name='vendors' AND constraint_type='PRIMARY KEY'
  ) THEN
    EXECUTE 'ALTER TABLE public.vendors ADD PRIMARY KEY (vendor_id)';
  END IF;
END$$;

DO $$
BEGIN
  -- Vendor clients: ensure id is identity and primary key
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='vendor_clients' AND column_name='id'
  ) THEN
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema='public' AND table_name='vendor_clients' AND column_name='id' AND is_identity='YES'
    ) THEN
      BEGIN
        EXECUTE 'ALTER TABLE public.vendor_clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
      EXCEPTION WHEN others THEN
        NULL;
      END;
    END IF;

    IF NOT EXISTS (
      SELECT 1 FROM information_schema.table_constraints tc
      WHERE tc.table_schema='public' AND tc.table_name='vendor_clients' AND tc.constraint_type='PRIMARY KEY'
    ) THEN
      EXECUTE 'ALTER TABLE public.vendor_clients ADD PRIMARY KEY (id)';
    END IF;
  END IF;
END$$;

-- Helpful index for case-insensitive vendor name searches
CREATE INDEX IF NOT EXISTS idx_vendors_name_norm ON public.vendors (vendor_name_norm);
`
  try {
    await query(ddl)
    // Align the identity/sequence with current max values (best-effort)
    await query(`
      DO $$
      DECLARE v_max bigint;
      BEGIN
        SELECT COALESCE(MAX(vendor_id),0) + 1 INTO v_max FROM public.vendors;
        BEGIN
          EXECUTE 'SELECT setval(pg_get_serial_sequence(''public.vendors'',''vendor_id''), ' || v_max || ', false)';
        EXCEPTION WHEN others THEN NULL; END;
      END$$;`)
  } catch (e) {
    console.error('Migration ensureIdentity failed:', e.message)
  }
}

